config/routes.rb
Rails.application.routes.draw do
  resources :user_currency_conversions
  resources :friendships, only: [:create, :destroy]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"

  get "my_portfolio", to: "users#my_portfolio"
  get "my_friends", to: "users#my_friends"
  get "users/:id/portfolio", to: "users#portfolio"
  get "users/search", to: "users#search"

  get "currency_conversions/search", to: "currency_conversions#search"
end

app/views/friends/_search_result.html.erb
<table>
    <thead>
        <tr>
            <th>Full Name</th>
            <th>Email</th>
            <th>Portfolio</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @searched_users.each do |user| %>
            <% if user != current_user %>
                <tr>
                    <td><%= user.full_name %></td>
                    <td><%= user.email %></td>
                    <td><%= link_to "Show", "/users/#{user.id}/portfolio" %></td>
                    <% if current_user.is_friends_with?(user) %>
                        <td><button disabled>Following</button></td>
                    <% else %>
                        <td><%= button_to "Follow", friendships_path, params: {user_id: current_user.id, friend_id: user.id} %></td>
                    <% end %>
                </tr>
            <% end %>
        <% end %>
    </tbody>
</table>
<br>
<%= will_paginate @searched_users, param_name: :users_page %>

app/views/friends/_table.html.erb
<table>
    <thead>
        <tr>
            <th>Full Name</th>
            <th>Email</th>
            <th>Portfolio</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @friends.each do |friend| %>
            <% friendship = Friendship.where(user_id: @user.id, friend_id: friend.id).first %>
            <tr>
                <td><%= friend.full_name %></td>
                <td><%= friend.email %></td>
                <td><%= link_to "Show", "/users/#{friend.id}/portfolio" %></td>
                <td><%= button_to "Stop following", friendship_path(friendship), data: { turbo_confirm: "Are you sure you want to stop following #{friend.full_name}?" }, method: :delete %></td>
            </tr>
        <% end %>
    </tbody>
</table>
<br>
<%= will_paginate @friends, param_name: :friends_page %>