config/routes.rb
Rails.application.routes.draw do
  resources :user_currency_conversions
  resources :friendships, only: [:create, :destroy]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"

  get "my_portfolio", to: "users#my_portfolio"
  get "my_friends", to: "users#my_friends"
  get "users/:id/portfolio", to: "users#portfolio"
  get "users/search", to: "users#search"

  get "currency_conversions/search", to: "currency_conversions#search"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_currency_conversions
  has_many :currency_conversion, through: :user_currency_conversions
  has_many :friendships
  has_many :friends, through: :friendships

  validates :first_name, :last_name, presence: true, length: { minimum: 2, maximum: 20 }

  def full_name
    "#{first_name} #{last_name}"
  end

  def is_friends_with?(user)
    true if self.friends.find_by(id: user.id)
  end

  def track_currency_conversion?(currency_conversion)
    true if self.currency_conversion.find_by(id: currency_conversion.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @currency_conversions = @user.currency_conversion
  end

  def my_friends
    @user = current_user
    @friends = @user.friends.paginate(page: params[:friends_page], per_page: 10)
  end

  def portfolio
    @user = User.find_by(id: params[:id])
    if !@user
      flash[:alert] = "You don't have enough permission to perform this action."
      redirect_to my_friends_path, allow_other_host: true
    else
      @currency_conversions = @user.currency_conversion
      if @user == current_user then redirect_to my_portfolio_path end
    end
  end

  def search
    @user = current_user
    @friends = @user.friends.paginate(page: params[:friends_page], per_page: 10)

    pattern = "%#{params[:query]}%"
    @searched_users = User.where("first_name LIKE ? OR last_name LIKE ? OR email LIKE ?", pattern, pattern, pattern).paginate(page: params[:users_page], per_page: 10)
    render "users/my_friends"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/my_friends.html.erb
<h1>My Friends</h1>

<% if @friends && !@friends.empty? %>
    <%= render "friends/table" %>
<% else %>
    <p>Your friends list is currently empty.</p>
<% end %>

<h2>Search for a new friend:</h2>

<%= form_with url: users_search_path, method: :get do |form| %>
  <%= form.label :query, "Enter a name/email:" %>
  <br>
  <%= form.text_field :query %>

  <%= form.submit "Search" %>
<% end %>
<br>
<% if @searched_users && !@searched_users.empty? %>
    <%= render "friends/search_result" %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<% if @currency_conversions && !@currency_conversions.empty? %>
    <%= render "currency_conversions/table" %>
<% else %>
    <p>Your Portfolio is currently empty.</p>
<% end %>

<h2>Search for a Currency Conversion:</h2>

<%= form_with url: currency_conversions_search_path, method: :get do %>
  <% currency_options = ["AUD", "BRL", "CAD", "CHF", "CNY", "EUR", "GBP", "HKD", "INR", "JPY", "KRW", "MXN", "NOK", "NZD", "RUB", "SEK", "SGD", "TRY", "USD", "ZAR",] %>  
  <div>
    <%= label_tag :code, "Select the 1st currency code:" %>
    <%= select_tag :code, options_for_select(currency_options), prompt: "Choose a currency" %>
  </div>
  <br>

  <div>
    <%= label_tag :codein, "Select the 2nd currency code:" %>
    <%= select_tag :codein, options_for_select(currency_options), prompt: "Choose a currency" %>
  </div>
  <br>

  <%= submit_tag "Search" %>
<% end %>
<br>

<% if @currency_conversion %>
    <%= render "currency_conversions/search_result" %>
<% end %>

app/views/users/portfolio.html.erb
<h1><%= @user.full_name %>'s Portfolio</h1>

<% if current_user.is_friends_with?(@user) %>
    <td><button disabled>Following</button></td>
<% else %>
    <td><%= button_to "Follow", friendships_path, params: {user_id: current_user.id, friend_id: @user.id} %></td>
<% end %>

<br><br><br>

<% if @currency_conversions && !@currency_conversions.empty? %>
    <%= render "currency_conversions/table" %>
<% else %>
    <p><%= @user.full_name %>'s Portfolio is currently empty.</p>
<% end %>
<br>
<%= link_to "⇐ Return", my_friends_path %>