config/routes.rb
Rails.application.routes.draw do
  resources :user_currency_conversions
  resources :friendships, only: [:create, :destroy]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"

  get "my_portfolio", to: "users#my_portfolio"
  get "my_friends", to: "users#my_friends"
  get "users/:id/portfolio", to: "users#portfolio"
  get "users/search", to: "users#search"

  get "currency_conversions/search", to: "currency_conversions#search"
end

app/models/currency_conversion.rb
require 'httparty'

class CurrencyConversion < ApplicationRecord
  has_many :user_currency_conversions
  has_many :user, through: :user_currency_conversions

  def self.fetch_and_create(code, codein)
    response = HTTParty.get("https://economia.awesomeapi.com.br/last/#{code}-#{codein}")

    if response.success?
      conversion_code = code + codein
      high_level_key = response[conversion_code]
      current_currency_conversion = self.find_by(conversion_code: conversion_code)

      if current_currency_conversion
        current_currency_conversion.update(
          high: high_level_key["high"],
          low: high_level_key["low"],
          last_updated_at: high_level_key["create_date"])

        return current_currency_conversion 
      else 
        self.create(
          conversion_code: conversion_code,
          code: high_level_key["code"],
          codein: high_level_key["codein"],
          high: high_level_key["high"],
          low: high_level_key["low"],
          last_updated_at: high_level_key["create_date"])

        return CurrencyConversion.last  
      end
    end
  end
end

app/controllers/currency_conversions_controller.rb
class CurrencyConversionsController < ApplicationController
  def search
    @user = current_user
    @currency_conversion = CurrencyConversion.fetch_and_create(params[:code], params[:codein])
    @currency_conversions = @user.currency_conversion

    if !@currency_conversion
      flash[:alert] = "Please enter valid currency codes."
    end

    render "users/my_portfolio"
  end
end

app/helpers/currency_conversions_helper.rb
module CurrencyConversionsHelper
end

app/views/currency_conversions/_search_result.html.erb
<div style="border: solid 1px black">
    <h4><%= @currency_conversion.conversion_code %></h4>
    <p>
        <span><strong>Code: </strong><%= @currency_conversion.code %>;</span>
        <span><strong>Codein: </strong><%= @currency_conversion.codein %>;</span>
        <span><strong>High: </strong><%= @currency_conversion.high %>;</span>
        <span><strong>Low: </strong><%= @currency_conversion.low %>.</span>
    </p>
    <% user_has_currency_conversion = !UserCurrencyConversion.where(user_id: current_user.id, currency_conversion_id: @currency_conversion.id).empty? %>
    <% if !user_has_currency_conversion %>
        <% if current_user.currency_conversion.count >= 10 %>
            <button disabled=true>Add to Portfolio</button>
            <span>*<code>You can only track up to 10 Currency Conversions.</code></span>
        <% else %>
            <%= button_to "Add to Portfolio", user_currency_conversions_path, 
            params: { user_id: current_user.id, currency_conversion_id: @currency_conversion.id } %>
        <% end %>
    <% end %>
</div>

app/views/currency_conversions/_table.html.erb
<table>
    <thead>
        <tr>
        <th></th>
        <th>Code</th>
        <th>High</th>
        <th>Low</th>
        <th>Last updated at</th>
        <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @currency_conversions.each_with_index do |currency_conversion, index| %>
            <% user_currency_conversion = UserCurrencyConversion.where(user_id: @user.id, currency_conversion_id: currency_conversion.id).first %>
            <tr>
                <td><%= index + 1 %></td>
                <th><%= currency_conversion.conversion_code %></th>
                <td><%= currency_conversion.high %></td>
                <td><%= currency_conversion.low %></td>
                <td><%= currency_conversion.last_updated_at %></td>
                <% if is_current_user(@user.id) %>
                    <td><%= button_to "Remove", user_currency_conversion_path(user_currency_conversion), data: { turbo_confirm: "Are you sure you want to stop tracking #{currency_conversion.conversion_code}?" }, method: :delete %></td>
                <% elsif !current_user.track_currency_conversion?(currency_conversion) %>
                    <td>
                        <%= button_to "Track", user_currency_conversions_path, 
                            params: { user_id: current_user.id, currency_conversion_id: currency_conversion.id } %>
                    </td>
                <% else %>
                    <td><button disabled>Tracking</button></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>