config/routes.rb
Rails.application.routes.draw do
  resources :user_currency_conversions
  resources :friendships, only: [:create, :destroy]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"

  get "my_portfolio", to: "users#my_portfolio"
  get "my_friends", to: "users#my_friends"
  get "users/:id/portfolio", to: "users#portfolio"
  get "users/search", to: "users#search"

  get "currency_conversions/search", to: "currency_conversions#search"
end

app/views/layouts/_navbar.html.erb
<nav>
    <p><strong>Finance Tracker</strong></p>
    <% if signed_in? %>
      <code>[<%= current_user.full_name %>]</code>
        <ul>
          <li>
            <%= link_to "Home", root_path %>
          </li>
          <li>
            <%= link_to "Portfolio", my_portfolio_path %>
          </li>
          <li>
            <%= link_to "Friends", my_friends_path %>
          </li>
          <li>
            <%= link_to "Profile", edit_user_registration_path %>
          </li>
          <li>
            <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete } %>
          </li>
        </ul>
    <% end %>
</nav>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Finance Tracker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>